### PR TITLE
Add support to ActiveJob sidekiq adapter

### PR DESCRIPTION
**Pull request by mirubiri**
Add support to ActiveJob.

This PR uses the same method Sidekiq uses to add logging, check: [Sidekiq logger.rb file](https://github.com/mperham/sidekiq/blob/3b5ae30c4e5e9e760268243ab5c14664a2f8d236/lib/sidekiq/job_logger.rb#L41)

### CODE REVIEW

**Review by seanhandley — APPROVED** [review]

**Comment by annawinkler** [comment]
@mirubiri Thank you for your PR! I have recently updated the default branch for this project to `main`. Could you please update your PR to target `fastly:main`? Alternatively, I would be happy to update the PR for you. Thank you!

**Review by leklund — COMMENTED** [review]
@mirubiri Thanks! This looks great.

If you could please re-create this PR to target `fastly:main` I can merge and release

**Comment by leklund** [comment]
Re-opened here #22. I'll get this merged and released.

**Comment by mirubiri** [comment]
@annawinkler @leklund Sorry for not making the changes myself, I didn't get the notifications 🙏

**Pull request closed without merging**
