### PR TITLE
Fix compatibility with Ruby 3.0.0

### PR DESCRIPTION
**Pull request by Kevinrob**
This PR will:
* Fix issue with Ruby 3.0.0
* Add Ruby versions `2.6`, `2.7` and `3.0` to tests

### CODE REVIEW

**Comment by leklund** [comment]
Thanks for starting this! A quick glance at why the tests are failing and it's likely because I was passing a hash to the register method for the keyword args. This was deprecated in Ruby 2.7 and no longer works run 3.0. Adding a double-splat should fix the error.

Ex:
```
described_class.register(metric)
```

would become

```
described_class.register(**metric)
```

**Comment by Kevinrob** [comment]
@leklund Here you are! The PR is ready to be reviewed.
The tests are green with Ruby 3.0 🎉

**Comment by Kevinrob** [comment]
@leklund Is it possible de merge and tag a new release with this PR?

**Comment by leklund** [comment]
@Kevinrob Yes, I'll get this out today! Thanks for the PR!

**Review by leklund — APPROVED** [review]

**Comment by Kevinrob** [comment]
> @Kevinrob v1.4.0 has been released

Thank you! 🎉

**Pull request merged**
